"""create research metadata schema

Revision ID: 06d55de4f74f
Revises:
Create Date: 2026-09-29 14:32:54.287759

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "06d55de4f74f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_uri", sa.Text(), nullable=False),
        sa.Column("short_name", sa.Text(), nullable=True),
        sa.Column("full_name", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("release_date", sa.Date(), nullable=True),
        sa.Column("version_identifier", sa.String(length=128), nullable=True),
        sa.Column("version_innovation", sa.Text(), nullable=True),
        sa.Column("homepage", sa.Text(), nullable=True),
        sa.Column("how_to_cite", sa.Text(), nullable=True),
        sa.Column("source_type", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dataset_versions")),
        sa.UniqueConstraint("source_uri", name="uq_dataset_versions_source_uri"),
    )
    op.create_index(
        "ix_dataset_versions_release_date",
        "dataset_versions",
        ["release_date"],
        unique=False,
    )
    op.create_index(
        "ix_dataset_versions_source_type",
        "dataset_versions",
        ["source_type"],
        unique=False,
    )
    op.create_table(
        "ingest_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_uri", sa.Text(), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("schema_type", sa.String(length=128), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingest_snapshots")),
    )
    op.create_index(
        "ix_ingest_snapshots_source_uri_fetched_at",
        "ingest_snapshots",
        ["source_uri", "fetched_at"],
        unique=False,
    )
    op.create_table(
        "kg_entities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_uri", sa.Text(), nullable=False),
        sa.Column("source_uuid", sa.String(length=128), nullable=True),
        sa.Column("entity_type", sa.String(length=128), nullable=False),
        sa.Column("label", sa.Text(), nullable=True),
        sa.Column(
            "raw_payload",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kg_entities")),
        sa.UniqueConstraint("source_uri", name="uq_kg_entities_source_uri"),
    )
    op.create_index(
        "ix_kg_entities_entity_type", "kg_entities", ["entity_type"], unique=False
    )
    op.create_index(
        "ix_kg_entities_source_uuid", "kg_entities", ["source_uuid"], unique=False
    )
    op.create_table(
        "dataset_entity_links",
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.Column("entity_id", sa.Integer(), nullable=False),
        sa.Column("relation_type", sa.String(length=128), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset_versions.id"],
            name=op.f("fk_dataset_entity_links_dataset_id_dataset_versions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["entity_id"],
            ["kg_entities.id"],
            name=op.f("fk_dataset_entity_links_entity_id_kg_entities"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "dataset_id",
            "entity_id",
            "relation_type",
            "position",
            name=op.f("pk_dataset_entity_links"),
        ),
    )
    op.create_index(
        "ix_dataset_entity_links_relation_type",
        "dataset_entity_links",
        ["relation_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_dataset_entity_links_relation_type", table_name="dataset_entity_links"
    )
    op.drop_table("dataset_entity_links")
    op.drop_index("ix_kg_entities_source_uuid", table_name="kg_entities")
    op.drop_index("ix_kg_entities_entity_type", table_name="kg_entities")
    op.drop_table("kg_entities")
    op.drop_index(
        "ix_ingest_snapshots_source_uri_fetched_at", table_name="ingest_snapshots"
    )
    op.drop_table("ingest_snapshots")
    op.drop_index("ix_dataset_versions_source_type", table_name="dataset_versions")
    op.drop_index("ix_dataset_versions_release_date", table_name="dataset_versions")
    op.drop_table("dataset_versions")
    # ### end Alembic commands ###
